all:	mychmod \
	myclose \
	mydup \
	mydup2 \
	myfreopen \
	myopen \
	mypipe \
	mypipe2 \
	mypopen \
	myread \
	mystat \
	mystdio \
	myumask

clean:	
	rm -f mychmod myclose mydup mydup2 myfreopen myopen mypipe mypipe2 mypopen myread mystat mystdio myumask
