all:	myctime \
	mygetcwd \
	mygetenv \
	mygetpid \
	mygetpwuid \
	mygetrlimit \
	mygettimeofday \
	mygetuid \
	mylocaltime \
	mymaniptime \
	mypathconf \
	myputenv \
	mystrftime \
	mystrftime2 \
	mysysconf \
	mysysinfo \
	mytime \
	mytimes \
	myuname \
	myunsetenv

clean:	
	rm myctime mygetcwd mygetenv mygetpid mygetpwuid mygetrlimit mygettimeofday mygetuid mylocaltime mymaniptime mypathconf myputenv mystrftime mystrftime2 mysysconf mysysinfo mytime mytimes myuname myunsetenv
