mycreate:	mycreate.c
	cc -Wno-int-to-pointer-cast -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -o mycreate mycreate.c -lpthread

exercise01:	exercise01.c
	cc -Wno-int-to-pointer-cast -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -o exercise01 exercise01.c -lpthread

exercise02:	exercise02.c
	cc -Wno-int-to-pointer-cast -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -o exercise02 exercise02.c -lpthread

exercise03:	exercise03.c
	cc -Wno-int-to-pointer-cast -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -o exercise03 exercise03.c -lpthread

exercise04:	exercise04.c
	cc -Wno-int-to-pointer-cast -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -o exercise04 exercise04.c -lpthread

exercise05:	exercise05.c
	cc -Wno-int-to-pointer-cast -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -o exercise05 exercise05.c -lpthread

clean:	
	rm -f mycreate
