all:	badlibcall \
	badtime \
	myarray \
	myatoi \
	mylibcall \
	mymalloc \
	myparse \
	myperror \
	mypointer \
	mystrerror \
	mystring \
	mystrtok \
	mystrtok2 \
	mytime \
	neverauto

clean:	
	rm -f badlibcall badtime myarray myatoi mylibcall mymalloc myparse myperror mypointer mystrerror mystring mystrtok mystrtok2 mytime neverauto
